/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsSlugRouteImport } from './routes/apps.$slug'
import { Route as ApiPublicScrapeRouteImport } from './routes/api/public/scrape'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSlugRoute = AppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScrapeRoute = ApiPublicScrapeRouteImport.update({
  id: '/api/public/scrape',
  path: '/api/public/scrape',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/api/public/scrape': typeof ApiPublicScrapeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/api/public/scrape': typeof ApiPublicScrapeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/api/public/scrape': typeof ApiPublicScrapeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/apps/$slug' | '/api/public/scrape'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/apps/$slug' | '/api/public/scrape'
  id: '__root__' | '/' | '/apps/$slug' | '/api/public/scrape'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsSlugRoute: typeof AppsSlugRoute
  ApiPublicScrapeRoute: typeof ApiPublicScrapeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$slug': {
      id: '/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scrape': {
      id: '/api/public/scrape'
      path: '/api/public/scrape'
      fullPath: '/api/public/scrape'
      preLoaderRoute: typeof ApiPublicScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsSlugRoute: AppsSlugRoute,
  ApiPublicScrapeRoute: ApiPublicScrapeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
