/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsSlugRouteImport } from './routes/apps.$slug'
import { Route as ApiPublicScrapeRouteImport } from './routes/api/public/scrape'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSlugRoute = AppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScrapeRoute = ApiPublicScrapeRouteImport.update({
  id: '/api/public/scrape',
  path: '/api/public/scrape',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/api/public/scrape': typeof ApiPublicScrapeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/api/public/scrape': typeof ApiPublicScrapeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/api/public/scrape': typeof ApiPublicScrapeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/login' | '/apps/$slug' | '/api/public/scrape'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/login' | '/apps/$slug' | '/api/public/scrape'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/apps/$slug'
    | '/api/public/scrape'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  AppsSlugRoute: typeof AppsSlugRoute
  ApiPublicScrapeRoute: typeof ApiPublicScrapeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$slug': {
      id: '/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/scrape': {
      id: '/api/public/scrape'
      path: '/api/public/scrape'
      fullPath: '/api/public/scrape'
      preLoaderRoute: typeof ApiPublicScrapeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  AppsSlugRoute: AppsSlugRoute,
  ApiPublicScrapeRoute: ApiPublicScrapeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
